# -*- coding: utf-8 -*-
"""studentperformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Px6Da0fUWK85mownHirOQFikwEWTylhi
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/StudentsPerformance.csv")
df

df.head()

df.describe()

df.info()

score_columns = ['math score', 'reading score', 'writing score']
df[score_columns].describe()

df.tail()

df[score_columns].mean()

df[score_columns].mode()

df[score_columns].quantile(0.25)

df["Total score"] = (df["math score"] + df["reading score"] + df["writing score"])

df.columns

df["precentage"]=(df["Total score "]/300)*100

df[["Total score","precentage"]].head()

